"""users table

Revision ID: a85e550c9a5a
Revises: 
Create Date: 2019-05-11 15:28:11.732296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85e550c9a5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('processed_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_processed_songs_create_date'), 'processed_songs', ['create_date'], unique=False)
    op.create_index(op.f('ix_processed_songs_name'), 'processed_songs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_songs_name'), table_name='processed_songs')
    op.drop_index(op.f('ix_processed_songs_create_date'), table_name='processed_songs')
    op.drop_table('processed_songs')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
